name: Docker build image

on: push

jobs:
  hellow-world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello-world
        run: echo "Hello, world."
      - name: Print current dir
        run: pwd
      - name: Check out repo
        uses: actions/checkout@v3
      - name: list file
        run: ls -la
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/academy-learnhub-api:${{ github.sha }}
